name: Build and push react image

on:
  push:
    branches:
      - main

  workflow_dispatch:

env:
  DOCKER_IMAGE: edcilo/react

jobs:
  image:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.meta.outputs.version }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3.5.0
        with:
          images: ${{ env.DOCKER_IMAGE }}

      - name: Version
        run: echo ${{ steps.meta.outputs.version }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.7.0
        with:
          context: ./front-shopping-cart
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
